#!/bin/bash 
#SBATCH --mem=100G
#SBATCH -J SNP_calling

home=('/nbi/Research-Groups/JIC/Diane-Saunders/kai/maprice/Raw_data/samples') #Give working directory


#source picard-1.134
#source python-3.5.1 


for name in `cat $home/list.txt`
	
	do

	 	#sbatch -p RG-Diane-Saunders $home/SCRIPTS/SNP_calling/SNPpipeline1.sh -n $name 
		sbatch -p nbi-medium SCRIPTS/SNP_calling/SNPpipeline1.sh -n $name -g /nbi/Research-Groups/JIC/Diane-Saunders/kai/maprice/Raw_data/samples/Oryza_sativa/Oryza_sativa -l

		echo "done with ${name}"
	
		

	done
